### ISSUE TITLE
Do fizzbuzz with, if for statments 

### ISSUE THREAD

**Issue by dg60866090** [dg60866090/team-fizzbuzz#1]
##Tasks

- [ ] Print 'fizz' if i is times of 3 
- [ ] Print 'buzz' if i is times of 5
- [ ] Print 'fizzbuzz' if i is times of 15
- [ ]  While i goes up 1 to 16 
- [ ] else, Print i itself.
